variables:
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe'
  VSTEST_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
  UNITTEST_FOLDER: '.\src\AcelistUnitTest\bin\Release\net6.0-windows'

stages:
  - build
  - test

build_job:
  stage: build
  script:
    - '& "$env:NUGET_PATH" restore .\src\Acelist.sln'
    - '& "$env:MSBUILD_PATH" .\src\Acelist.sln /p:Configuration=Release'
  artifacts:
    expire_in: 2 days
    paths:
      - '$env:UNITTEST_FOLDER'

test_job:
  stage: test
  script:
    - '& "$env:VSTEST_PATH" "$env:UNITTEST_FOLDER\AcelistUnitTest.dll"'
  dependencies:
    - build_job