variables:
   MSBUILD_PATH: 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe'
 
stages:
  - build
  - deploy
 
build_job:
  stage: build
  tags:
    - test
  script:
    - '& "$env:MSBUILD_PATH" ".\src\Acelist.sln" /p:Configuration=Release'
  artifacts:
    expire_in: 2 days
    paths:
      - '.\src\Acelist\bin\Release\'
  allow_failure:
    exit_codes: 2