variables:
  PROJECT_NAME: '.src\Acelist.sln'
before_script:
  - echo "starting build for Acelist"
  - echo "Restoring NuGet Packages..."
  - C:\NuGet\nuget.exe restore "%PROJECT_NAME%"
stages:
  - build
  - test
build:
  stage: build
  script:
  - echo "Release build..."
  - '"C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "%PROJECT_NAME%"'
  artifacts:
    untracked: true
test:
  stage: test
  script:
  - echo "starting tests"
  - cd .\src\AcelistUnitTest\bin\Release\net6.0-windows
  - '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\MSTest.exe" /testcontainer:AcelistUnitTest.dll'
  dependencies:
  - build